force-app/main/default/objects/ForecastItem__c/ForecastItem__c.object-meta.xml
<CustomObject>
    <label>Forecast Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forecast Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ForecastItem__c/fields/Temp_max__c.field-meta.xml
<CustomField>
    <fullName>Temp_max__c</fullName>
    <label>Temp max</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ForecastItem__c/fields/Temp_min__c.field-meta.xml
<CustomField>
    <fullName>Temp_min__c</fullName>
    <label>Temp min</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ForecastItem__c/fields/Weather_condition__c.field-meta.xml
<CustomField>
    <fullName>Weather_condition__c</fullName>
    <label>Weather condition</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WeatherController.cls
public with sharing class WeatherController {
    @AuraEnabled(cacheable=true)
    public static List<ForecastItem__c> getWeatherResults(String city) {
            Date day = Date.today();
            return [
                SELECT Date__c, Temp_min__c, Temp_max__c, Weather_condition__c, City__c
                FROM ForecastItem__c
                WHERE Date__c >= :day
                AND City__c = :city
                WITH SECURITY_ENFORCED
                LIMIT 5
                ];
            }
}